name: Pipeline CI/CD - Projeto Fatec

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pudim:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Inicia o container em segundo plano (-d) e valida se o Nginx está a responder
      - name: Validar container em execução
        run: |
          docker run -d -p 80:80 --name test-container ${{ secrets.DOCKER_USER }}/pudim:latest
          sleep 3
          curl -f http://localhost:80 || exit 1